### ISSUE TITLE
Feature request: binding for same key with different pressed times

### ISSUE THREAD

**Issue by QiangF** [zw963/linux_key_rebinding#1]
Hello sir,
There is a program called xcape. It can generate the Escape key when Left Control is pressed and released on its own. Can you add that to linux_key_rebinding and make it also generate key combinations (such as C-c) if the modifier key is pressed and released on its own.
Thank you!

**Comment by zw963** [comment]
Hi, this repo is just a collection of some useful package and very little improved.

I still no time to reserch how to add this new function to [rbindkeys](https://github.com/kui/rbindkeys)

Maybe add a new issue directly to the origional author repo is a more better idea.

**Comment by QiangF** [comment]
No problem. Current xcape works pretty well with rbindkeys.
Thank you!
