### ISSUE TITLE
Help: how to make it work in a remote session

### ISSUE THREAD

**Issue by QiangF** [zw963/linux_key_rebinding#2]
Hello everyone,
Is it possible to make the keybinding work in an x2go session?
Thank you!

**Comment by zw963** [comment]
rbindkeys is worked together another package:  active_window_x.

you need decide how to rebinding one key accroding to `app_class`
`title` or `app_name`. you can get those useful infomation from rbindkeys
log with command:  `rbindkeys` (Notice: no --daemon is required)

and binding key like this in ~/.rbindkeys:

``` ruby
bind_key [KEY_LEFTALT, KEY_BACKSPACE] do |_evt, op|
    if app_class =~ /terminal/i and title =~ /nano/
      # enable mark mode in nano
      op.combination_key [KEY_LEFTSHIFT, KEY_LEFTCTRL, KEY_6]
      # move a word backward
      op.combination_key [KEY_LEFTALT, KEY_J]
      # kill it.
      op.combination_key [KEY_LEFTCTRL, KEY_K]
    elsif app_class =~ /terminal/i
      :through
    else
      op.combination_key [KEY_LEFTCTRL, KEY_BACKSPACE]
    end
  end
```

**Comment by zw963** [comment]
If those application app name is too general, you even could specify a new name
use a bash shell wrapper. 

e.g.

``` sh
#!/bin/sh

exec -a 'this_is_x2go' /full/path/of/x2go --some-argument
```

then use those wrapper to start x2go.

I hope could help.

**Comment by QiangF** [comment]
Thank  you Sir.  The problem is x2go doesn't change window title dynamically. For example, if I switched to Emacs on the remote desktop, the x2go window's title is still x2go,  rbindkeys won't know I have switched application on the remote machine.
One possible solution is to make x2go change its window title to the window in focus on the remote side.  I will post back if I found the way to do it.
